[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 256
seed = '0x2'
# By setting the seed, for this seed every time same random number will be applied in order.
# If seed is not set, random numbers will not be in order and code will break for different resons. 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
